services:
  app:
    network_mode: host
    container_name: justniffer
    image: onotelli/justniffer:0.6.7

    volumes:
      - justniffer:/opt/justniffer/
      - ..:/workspace
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
      

volumes:
  justniffer: