
extractors:
  RequestTimestamp:
  ConnectionID:
  ConnectionState:
  CloseOriginator:
  ConnectionRequests:
  SourceIPPort:
  DestIPPort:
  ConnectionTime:
  RequestTime:
  ResponseTime:
  Idle1Time:
  Idle2Time:
  ConnectionDuration:
  RequestSize:
  ResponseSize:
  ProtocolSelector:
    selectors:
      TLSInfoExtractor:
      HttpInfoExtractor:
      SSHInfoExtractor:
      PlainTextExtractor:
        length: 20
formatter: 
  str:
    sep: ' '
    null_value: '-'
  # str:
  #   sep: ' | '
  #   null_value: 'N/A'
